apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-marketplace-deployment
  namespace: online-marketplace-ns
  labels:
    app: online-marketplace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: online-marketplace
  template:
    metadata:
      labels:
        app: online-marketplace
    spec:
      imagePullSecrets:
        - name: acr-auth
      containers:
      - name: online-marketplace-image
        image: sandboxregistry1234.azurecr.io/onlinemarketplace:v2
        ports:
        - containerPort: 3000
        env:
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              name: application-secrets
              key: JWT_KEY
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: application-secrets
              key: PORT
        - name: MONGO_DEV_URL
          valueFrom:
            secretKeyRef:
              name: application-secrets
              key: MONGO_DEV_URL
        - name: ACCOUNT_NAME
          valueFrom:
            secretKeyRef:
              name: application-secrets
              key: ACCOUNT_NAME
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: application-secrets
              key: DATABASE_NAME
        - name: KEY
          valueFrom:
            secretKeyRef:
              name: application-secrets
              key: KEY
              