apiVersion: v1
kind: Service
metadata:
  name: online-marketplace-service
  namespace: online-marketplace-ns
spec:
  selector:
    app: online-marketplace
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer